name: Build Docker Images

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: balancerd-staging
  PROJECT_NAME: temporal-registry
  REGION: europe-west3

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: google-github-actions/setup-gcloud@v0
        with:
          version: "359.0.0"
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_STAGING }}

      - name: "Install gcloud beta"
        run: gcloud components install beta

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_STAGING }}

      - name: Prepare build args
        id: build_args
        run: |
          github_sha_short=${GITHUB_SHA:0:7}
          push=${{ github.event_name == 'push' && !env.ACT }}
          echo "::set-output name=commit_sha_short::$github_sha_short"
          echo "::set-output name=image_tag::sha-$github_sha_short"
          echo "::set-output name=push::$push"

### BUILD & PUSH SERVER IMAGE ###

      - name: Build-Push Server image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: server.Dockerfile
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/server:${{ github.sha }}

### BUILD & PUSH ADMIN TOOLS IMAGE ###

      - name: Build-Push Admin Tools
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: admin-tools.Dockerfile
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/admin-tools:${{ github.sha }}
          build-args: |
            SERVER_IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/server:${{ github.sha }}

### BUILD & PUSH AUTO SETUP IMAGE ###

      - name: Build-Push Auto Setup
        if: steps.build_args.outputs.push == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: auto-setup.Dockerfile
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/auto-setup:${{ github.sha }}
          build-args: |
            SERVER_IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/server:${{ github.sha }}
            ADMIN_TOOLS_IMAGE=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.PROJECT_NAME }}/admin-tools:${{ github.sha }}
